version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: pharmacy       
      MYSQL_ROOT_PASSWORD: Mypass@123!
      MYSQL_USER: root
      MYSQL_PASSWORD: Mypass@123!
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
