---

apiVersion: v1
kind: Pod
metadata:
  name: pharmacy
spec:
  containers:
  - name: pharmacy
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=git://github.com/Nikitas-git/pharmacy.git",
           "--destination=kanikodemo/latest"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json


