---

apiVersion: v1
kind: Pod
metadata:
  name: kanikobattleships
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: ["--context=git://github.com/Nikitas-git/kanikoaws.git",
            "--destination=nikitadockermain/pharmacy_aws"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json

